# fly.toml file generated for rodosol-telegram-bot on 2023-02-16T23:45:47+01:00

app = "rodosol-telegram-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  TELEGRAM_BOT_NAME="rodosol_bot"
  RUST_LOG="rodosol_telegram_bot"

[experimental]
  auto_rollback = true

[checks]
  [checks.tcp_check]
    grace_period = "30s"
    interval = "15s"
    port = 8080
    timeout = "10s"
    type = "tcp"